### PR TITLE
Use Ubuntu-22.04 as the source image and Revert MACAddressPolicy to none

### PR DESCRIPTION
**Pull request by mboukhalfa**
On Ubuntu 22.04 the mac address generation for Linux bridge is persistent but that makes all our nodes bridge generate the same mac address which broke our network this PR changes the mac address generation to none so the bridge will inherit the mac address of the first attached interface

### CODE REVIEW

**Comment by kashifest** [comment]
Can you find and replace all occurences? I can see atleast one more file 
https://github.com/Nordix/metal3-dev-tools/blob/c75927204b083df097761e274fdb4594c0ed297f/ci/scripts/image_scripts/provision_base_image.sh#L5

**Comment by kashifest** [comment]
/retitle Use Ubuntu-22.04 as the source image and Revert MACAddressPolicy to none

**Review by kashifest — APPROVED** [review]

**Comment by kashifest** [comment]
Approved, would you want to run metal3-dev-tools test here or you are satisfied?

**Comment by mboukhalfa** [comment]
> Approved, would you want to run metal3-dev-tools test here or you are satisfied?

ok let me run the test

**Pull request merged**
