### PR TITLE
Test packer disconnect config

### PR DESCRIPTION
**Pull request by Sunnatillo**

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/test-integration-metal3-dev-tools-centos
//test-integration-metal3-dev-tools-ubuntu

**Comment by tuminoid** [comment]
The network issues we're having are not packer issues nor solvable in packer. While we may be able to fix a build sometimes, I don't think this is worth the effort.

**Comment by Sunnatillo** [comment]
> The network issues we're having are not packer issues nor solvable in packer. While we may be able to fix a build sometimes, I don't think this is worth the effort.

Agree.

**Pull request closed without merging**
