### PR TITLE
update ubuntu source image used for base image

### PR DESCRIPTION
**Pull request by Rozzii**
This commit only does what the title say.

### CODE REVIEW

**Review by tuminoid — APPROVED** [review]
/lgtm

**Comment by Rozzii** [comment]
centos test is irrelevant for this PR, CI infra is still not working correctly, I will just ignore the centos test
/override test-integration-metal3-dev-tools-centos

**Comment by Rozzii** [comment]
Give github  review approval please not labels.

**Review by kashifest — APPROVED** [review]
/approve

**Pull request merged**
