### PR TITLE
Change the credentials use for quay in container image build pipeline

### PR DESCRIPTION
**Pull request by mquhuy**
This takes into use the new quay credentials

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
/approve

**Comment by mquhuy** [comment]
/cc @kashifest @lentzi90 @smoshiur1237 @Rozzii @adilGhaffarDev 

Could someone trigger the tests for me as well?

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
