### PR TITLE
Add huutomerkki to assignees list and fix renovate config

### PR DESCRIPTION
**Pull request by Sunnatillo**
fixes https://github.com/Nordix/metal3-dev-tools/issues/664

### CODE REVIEW

**Review by tuminoid — DISMISSED** [review]

**Review by tuminoid — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
Needs more fixes on project-infra to pass tests.

```console
+ ./jenkins/scripts/fetch_logs.sh
./jenkins/scripts/fetch_logs.sh: line 31: GINKGO_FOCUS: unbound variable
```

**Comment by tuminoid** [comment]
New try after https://github.com/metal3-io/project-infra/pull/571 lands

**Pull request merged**
