### PR TITLE
Remove tools moved to metal3-clusterapi-docs

### PR DESCRIPTION
**Pull request by mboukhalfa**
We are simplifying Nordix repos! This repo is being removed and the content is being moved to project-infra and metal3-clusterapi-docs.
This PR removes moved tools to metal3-clusterapi-docs

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/hold 
waiting for https://github.com/Nordix/metal3-clusterapi-docs/pull/98

**Comment by tuminoid** [comment]
/override test-integration-metal3-dev-tools-centos test-integration-metal3-dev-tools-ubuntu

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by mboukhalfa** [comment]
/hold cancel 
PR merged

**Pull request merged**
