### PR TITLE
Remove packer based image building scripts

### PR DESCRIPTION
**Pull request by Sunnatillo**
Also removes 
- packer docker image building scripts
- dev env integration tests related files

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by Rozzii** [comment]
Nice job @Sunnatillo  and @NymanRobin for getting rid of Packer.
/lgtm

**Comment by Rozzii** [comment]
Integration tests are not relevant for the packer code removal.
/override test-integration-metal3-dev-tools-centos
/override test-integration-metal3-dev-tools-ubuntu

**Pull request merged**
