### PR TITLE
Add owners file and fix shellcheck issues

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by tuminoid — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
image
this should be configured in the GitHub repo settings I believe

**Comment by kashifest** [comment]
> image this should be configured in the GitHub repo settings I believe

its done already, replied in slack

**Comment by furkatgofurov7** [comment]
/test-integration-metal3-dev-tools-ubuntu

I configured the branch to make the above job as required since it will be added with the https://github.com/metal3-io/project-infra/pull/470

**Pull request merged**
