### PR TITLE
Install jenkins image related packages to ubuntu base image

### PR DESCRIPTION
**Pull request by Sunnatillo**
This change is related to a CI change where jobs will be run in directly in jenkins worker.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/overide-test-integration-metal3-dev-tools-centos

testing. Anyway this test does not check the changes.

**Comment by Sunnatillo** [comment]
/override-test-integration-metal3-dev-tools-centos

testing. Anyway the tests does not check the changes

**Comment by tuminoid** [comment]
@Sunnatillo: Do we still need this or no?

**Comment by Sunnatillo** [comment]
> @Sunnatillo: Do we still need this or no?

I am working on disk image builder. If there things go smooth and quick then, no. .

**Comment by Sunnatillo** [comment]
/close
not relevant anymore

**Pull request closed without merging**
