### PR TITLE
Bump CRICTL Version to v1.26.0 and add  CRIO_Version as a separate variable

### PR DESCRIPTION
**Pull request by kashifest**
Bump CRICTL to v1.26.0 and add CRIO_Version as a separate variable. This is since CRICTL_VERSION and CRIO_VERSION do not go 1 on 1 anymore

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
