### PR TITLE
Change node image network config to keyfile format in centos

### PR DESCRIPTION
**Pull request by Sunnatillo**
This PR solves issue of two connection profiles competing for eth0 interface. We set lower priority to System-eth0.nmconnection profile. 
The dev-env part of the solution is [here](https://github.com/metal3-io/metal3-dev-env/pull/1062)

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]
LGTM! Good job!

**Pull request merged**
