### PR TITLE
Add release-1.4 branch updates

### PR DESCRIPTION
**Pull request by kashifest**
Adds release-1.4 branch for downstream fork sync.

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
@Sunnatillo please approve this.

**Comment by kashifest** [comment]
/hold
Need to remove the test commit once reviewers are happy.

**Comment by kashifest** [comment]
This PR needs the dev-env PR https://github.com/metal3-io/metal3-dev-env/pull/1220. I have tested it with a test commit to use the branch. Here are the test run logs which passed. 
https://jenkins.nordix.org/job/metal3_dev_tools_integration_test_centos/238/
https://jenkins.nordix.org/job/metal3_dev_tools_integration_test_ubuntu/257/

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Pull request merged**
