### PR TITLE
remove moved machine-setup tools

### PR DESCRIPTION
**Pull request by mboukhalfa**
Moved to metal3-clusterapi-docs here https://github.com/Nordix/metal3-clusterapi-docs/pull/97

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/hold 
waiting for https://github.com/Nordix/metal3-clusterapi-docs/pull/97

**Review by tuminoid — APPROVED** [review]
Removal is held until the other one merges, so approving this.

/approve

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Comment by mboukhalfa** [comment]
/hold cancel 
The moving PR merged https://github.com/Nordix/metal3-clusterapi-docs/pull/97

**Pull request merged**
