### PR TITLE
add release-1.5 branches to sync

### PR DESCRIPTION
**Pull request by tuminoid**
Sync `release-1.5` branches from upstream to Nordix forks.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-integration-metal3-dev-tools-centos 
/override test-integration-metal3-dev-tools-ubuntu 

They do nothing here.

**Comment by tuminoid** [comment]
/hold
Until branches exist.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by lentzi90 — APPROVED** [review]
/approve

**Pull request merged**
