### PR TITLE
Bump k8s and related tools/images to v1.26.0

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by kashifest** [comment]
Passed tests: 
https://jenkins.nordix.org/job/metal3_dev_tools_integration_test_centos/151/console
https://jenkins.nordix.org/job/metal3_dev_tools_integration_test_ubuntu/184/console

**Review by lentzi90 — APPROVED** [review]

**Review by lentzi90 — DISMISSED** [review]

**Review by lentzi90 — APPROVED** [review]

**Pull request merged**
