### PR TITLE
:seedling: Remove release 1.5

### PR DESCRIPTION
**Pull request by mquhuy**
/hold

### CODE REVIEW

**Comment by tuminoid** [comment]
This again is doing two things at the same time. For sync job this is fine, but make the title and description about switching the release, and not just mention removing.

**Comment by tuminoid** [comment]
> This again is doing two things at the same time. For sync job this is fine, but make the title and description about switching the release, and not just mention removing.

OK, this is two commit PR again, which one is already in another PR to be first merged. So we're rebasing and then removing.

**Review by tuminoid — COMMENTED** [review]
/approve
Let's keep it held until we've cut final releases from 1.5 branches

**Review by kashifest — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — APPROVED** [review]
/approve

**Pull request merged**
