### PR TITLE
ironic image patching removed

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
ironic image patching removed.

### CODE REVIEW

**Comment by Rozzii** [comment]
Nice, just please remove the link to the job as that will become unavailable after some time,
/lgtm 
Also please don't forget to add the customization options for source based install in a followup .

**Review by Rozzii — APPROVED** [review]

**Comment by lentzi90** [comment]
See https://github.com/kubernetes/k8s.io/pull/4837

**Review by lentzi90 — APPROVED** [review]
/approve

**Review by mboukhalfa — APPROVED** [review]

**Pull request merged**
