### PR TITLE
image building improvements

### PR DESCRIPTION
**Pull request by tuminoid**
1. do not recreate keypair each time, it is conflicting between jobs
2. check if network detection fails, and abort before trying to call packer build, which would explode with cryptic issues"

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
/approve

**Review by kashifest — APPROVED** [review]
/approve

**Comment by tuminoid** [comment]
/hold
Let's not merge this yet so it doesn't mess with the tests during the weekend.

**Comment by tuminoid** [comment]
As expected, both builds failed to network errors thanks to CI. This is confirming that these changes do not affect that, but nonetheless these should be fixed. Keeping the hold over weekend.

**Comment by tuminoid** [comment]
/test-integration-metal3-dev-tools-centos
/test-integration-metal3-dev-tools-centos
Are these turned back on? Let's see...

**Comment by lentzi90** [comment]
Yeah I wonder... should we turn on the PR tests and leave the periodic tests? Then we can try things here when needed without destroying all our nightly jobs :slightly_smiling_face:

**Comment by tuminoid** [comment]
/unhold
If only the CI worked ...

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by Rozzii** [comment]
I am fine if we override the tests, this PR can be signed off by just human reviewers with high confidence.

**Comment by tuminoid** [comment]
I had high hopes that one by one these would work, like they did in two other PRs, but I guess not.

/override test-integration-metal3-dev-tools-centos
/override test-integration-metal3-dev-tools-ubuntu

**Pull request merged**
