### PR TITLE
Cleanup unused linter test related files

### PR DESCRIPTION
**Pull request by Sunnatillo**
Removes:
 - linter test pipeline
 - lint related docker image building scripts

### CODE REVIEW

**Comment by tuminoid** [comment]
Can you fix the Git commit message? Now it says `Remove outdated:`  which is not right.

**Review by lentzi90 — APPROVED** [review]
/approve

**Comment by Sunnatillo** [comment]
> Can you fix the Git commit message? Now it says `Remove outdated:` which is not right.

done

**Comment by tuminoid** [comment]
> > Can you fix the Git commit message? Now it says `Remove outdated:` which is not right.
> 
> done

Now it says: `cleanups unused:` so not better. You need to add title line, the current commit message goes into the body.

**Comment by Sunnatillo** [comment]
> > > Can you fix the Git commit message? Now it says `Remove outdated:` which is not right.
> > 
> > 
> > done
> 
> Now it says: `cleanups unused:` so not better. You need to add title line, the current commit message goes into the body.

it says: 
cleanups unused:
 - lint pipeline
 - go lint related docker image build scripts

**Comment by lentzi90** [comment]
> it says: cleanups unused:
> 
>     * lint pipeline
> 
>     * go lint related docker image build scripts

The problem is that this is not just one big text field. The first line is like a title and the title `cleanups unused:` does not make sense.

image

**Comment by Sunnatillo** [comment]
> > it says: cleanups unused:
> > ```
> > * lint pipeline
> > 
> > * go lint related docker image build scripts
> > ```
> 
> The problem is that this is not just one big text field. The first line is like a title and the title `cleanups unused:` does not make sense.
> 
> image
> 
> See https://git-scm.com/docs/git-commit#_discussion

I see. I have changed it now. Thanks for clarifying.

**Comment by tuminoid** [comment]
> > > it says: cleanups unused:
> > > ```
> > > * lint pipeline
> > > 
> > > * go lint related docker image build scripts
> > > ```
> > 
> > 
> > The problem is that this is not just one big text field. The first line is like a title and the title `cleanups unused:` does not make sense.
> > image
> > See https://git-scm.com/docs/git-commit#_discussion
> 
> I see. I have changed it now. Thanks for clarifying.

No need to change it further, but Git best practices say the title line should be 50 characters or less, and the body should be 72 characters per line. Just FYI.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by tuminoid — APPROVED** [review]

**Pull request merged**
