### PR TITLE
add ironic-image release branches to be synced

### PR DESCRIPTION
**Pull request by tuminoid**
Add release-23.1 release branch to be synced to Nordix.

### CODE REVIEW

**Comment by tuminoid** [comment]
/cc @smoshiur1237 @kashifest 
Please add approving reviews.

**Review by smoshiur1237 — APPROVED** [review]
/approve

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-integration-metal3-dev-tools-centos 
/override test-integration-metal3-dev-tools-ubuntu
Not relevant.

**Pull request merged**
